### ISSUE TITLE
Could not locate build.gradle used for Android project.

### ISSUE THREAD

**Issue by xxsnakerxx** [testfairy/testfairy-android-studio-plugin#2]
I have cordova based project and when I click on testfairy icon I receive the message in a console...

I think problem is that module name is hardcoded as 'app' here https://github.com/testfairy/testfairy-android-studio-plugin/commit/a0135d80d8d3786b7d46f75a16cb79a782810b35#diff-415b5e998446f5c3e97ebaca71c462e1R76

Android Studio 1.3 RC4
Gradle 1.2.3

**settings.gradle**
include ":"
include ":CordovaLib"

**Comment by kancic** [comment]
I have the same issue on 1.4 Preview 2.

**Comment by Gnzlt** [comment]
I have fixed it removing the colon from the includes, like this:

**settings.gradle**
include "app"
include "CordovaLib"

**Comment by AlmogBaku** [comment]
i'm still facing this issue. however @Gnzlt solution worked for me
